version: '2'

services:
  bitcoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  bitcoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-mainnet

  addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-testnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - bitcoin
      - addrindexrs

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - bitcoin-testnet
      - addrindexrs-testnet

  xcpdev-ssr:
    extends:
      file: docker-compose.tmpl.yml
      service: xcpdev-ssr-base-mainnet
    links:
      - bitcoin
      - addrindexrs

volumes:
  bitcoin-data:
  addrindexrs-data:
  counterparty-data:
